#!/bin/bash

IMAGE=jwilder/nginx-proxy

DOCKER_OPTS="--publish=80:80 \
             --publish=443:443 \
             --volume=/var/run/docker.sock:/tmp/docker.sock \
             --volume=/etc/waffle/nginx/certs:/etc/nginx/certs:ro \
             --volume=/etc/waffle/nginx/vhost.d:/etc/nginx/vhost.d:ro \
             --restart='on-failure[10]'"

source /etc/init.d/dockerized-local-service
