#!/bin/bash

stop() {
    service waffle-nginx stop
    service waffle-poxa stop
    service waffle-rally-integration stop
    service waffle-hedwig stop
    service waffle-hooks stop
    service waffle-api stop
    service waffle-app stop
}

start() {
    service waffle-nginx start
    service waffle-poxa start
    service waffle-rally-integration start
    service waffle-hedwig start
    service waffle-hooks start
    service waffle-api start
    service waffle-app start
}

status() {
    service waffle-nginx status
    service waffle-poxa status
    service waffle-rally-integration status
    service waffle-hedwig status
    service waffle-hooks status
    service waffle-api status
    service waffle-app status
}

case "$1" in
    start)
        start
        ;;

    stop)
        stop
        ;;

    status)
        status
        ;;

    restart)
        stop
        start
        ;;

    reload)
        stop
        start
        ;;

    *)
        echo "Usage: $0 {start|stop|status|reload|restart}"
        exit 1
        ;;
esac
exit $?
