#!/bin/bash

IMAGE=quay.io/waffleio/takeout-nginx

DOCKER_OPTS="--link waffle-app \
             --link waffle-api \
             --link waffle-hooks \
             --link waffle-poxa \
             --link waffle-hedwig \
             --link waffle-rally-integration \
             --publish=443:443 \
             --volume=/etc/waffle/nginx/certs:/etc/nginx/certs:ro \
             --restart='on-failure[10]'"

source /etc/init.d/dockerized-local-service
