#!/bin/bash

source /etc/waffle/port-mappings.list

IMAGE=quay.io/waffleio/waffle.io-rally-integration

DOCKER_OPTS="--env-file /etc/waffle/environment.list \
             --publish $RALLY_INTEGRATION_PORT:3001 \
             --restart='on-failure[10]'"

source /etc/init.d/dockerized-local-service
