#!/bin/bash

source /etc/waffle/port-mappings.list

IMAGE=quay.io/waffleio/waffle.io-hooks

DOCKER_OPTS="--env-file /etc/waffle/environment.list \
             --publish $HOOKS_PORT:3001 \
             --volume=/etc/waffle/ca-certificates:/etc/waffle/ca-certificates:ro \
             --restart='on-failure[10]'"

source /etc/init.d/dockerized-local-service
